import type { Beat, ServiceNode } from "./types";

export const SERVICES: ServiceNode[] = [
  { id: "support-rag", name: "support-rag", caps: ["rag", "tool_use"] },
  { id: "argus-review", name: "argus-review", caps: ["rag"] },
];

/**
 * The canonical pitch narrative — mirrors backend `aegis_platform.demo.run_demo()`.
 * Self-contained so Demo mode is deterministic and never depends on a live backend.
 */
export const NARRATIVE: Beat[] = [
  {
    id: "b1",
    title: "Prompt change tanks groundedness",
    serviceId: "support-rag",
    serviceName: "support-rag",
    incidentClass: "groundedness_regression",
    severity: "critical",
    riskTier: "L1",
    action: "rollback_prompt",
    usedAntibody: false,
    learnedAntibody: "ab-1",
    coveredClass: "groundedness_regression",
    mttr: 1.8,
    metricLabel: "groundedness",
    metricBad: "0.55",
    metricGood: "0.92",
    steps: [
      { stage: "detect", text: "anomaly · groundedness 0.92 → 0.55 (SPRT, conf 1.00)" },
      { stage: "perceive", text: "classified groundedness_regression [critical]" },
      { stage: "reason", text: "RCA · correlated with recent prompt change (rev-bad)" },
      { stage: "act", text: "governance L1 · auto · rollback_prompt → recovered" },
      { stage: "verify", text: "verified healthy · MTTR 1.8s" },
      { stage: "reflect", text: "postmortem written + filed prevention task" },
      { stage: "immunize", text: "🧬 fleet immunized · antibody ab-1" },
    ],
  },
  {
    id: "b2",
    title: "SAME failure class → Fleet Immunity",
    serviceId: "argus-review",
    serviceName: "argus-review",
    incidentClass: "groundedness_regression",
    severity: "critical",
    riskTier: "L1",
    action: "rollback_prompt",
    usedAntibody: true,
    mttr: 0.4,
    metricLabel: "groundedness",
    metricBad: "0.55",
    metricGood: "0.92",
    steps: [
      { stage: "detect", text: "anomaly · groundedness 0.92 → 0.55" },
      { stage: "perceive", text: "classified groundedness_regression [critical]" },
      { stage: "recall", text: "matched antibody ab-1 — skipping diagnosis (instant)" },
      { stage: "act", text: "governance L1 · auto · rollback_prompt → recovered" },
      { stage: "verify", text: "verified healthy · MTTR 0.4s" },
      { stage: "reflect", text: "antibody ab-1 reuse recorded (confidence ↑)" },
    ],
  },
  {
    id: "b3",
    title: "Cost explosion → model failover",
    serviceId: "support-rag",
    serviceName: "support-rag",
    incidentClass: "cost_explosion",
    severity: "critical",
    riskTier: "L1",
    action: "failover_model",
    usedAntibody: false,
    learnedAntibody: "ab-2",
    coveredClass: "cost_explosion",
    mttr: 2.1,
    metricLabel: "cost / req",
    metricBad: "$0.050",
    metricGood: "$0.010",
    steps: [
      { stage: "detect", text: "anomaly · cost/req $0.010 → $0.050 (CUSUM)" },
      { stage: "perceive", text: "classified cost_explosion [critical]" },
      { stage: "reason", text: "RCA · correlated with recent model change (rev-bad)" },
      { stage: "act", text: "governance L1 · auto · failover_model → recovered" },
      { stage: "verify", text: "verified healthy · MTTR 2.1s" },
      { stage: "reflect", text: "postmortem written" },
      { stage: "immunize", text: "🧬 fleet immunized · antibody ab-2" },
    ],
  },
  {
    id: "b4",
    title: "Corrupted index → L2 Governance gate",
    serviceId: "support-rag",
    serviceName: "support-rag",
    incidentClass: "dependency_outage",
    severity: "critical",
    riskTier: "L2",
    action: "rebuild_index",
    usedAntibody: false,
    awaitingApproval: true,
    blastRadius: "vector index rebuild — minutes of degraded recall (IRREVERSIBLE)",
    evidence: [
      "retrieval_health 0.98 → 0.30 (conf 1.00)",
      "config change rev-bad · 38s ago",
      "no matching antibody — novel failure",
    ],
    mttr: 0,
    metricLabel: "retrieval_health",
    metricBad: "0.30",
    metricGood: "0.98",
    steps: [
      { stage: "detect", text: "anomaly · retrieval_health 0.98 → 0.30" },
      { stage: "perceive", text: "classified dependency_outage [critical]" },
      { stage: "reason", text: "RCA · correlated with recent config change (rev-bad)" },
      { stage: "act", gate: true, text: "governance L2 · APPROVAL REQUIRED · rebuild_index" },
    ],
  },
  {
    id: "b5",
    title: "Human approves → rebuild index",
    serviceId: "support-rag",
    serviceName: "support-rag",
    incidentClass: "dependency_outage",
    severity: "critical",
    riskTier: "L2",
    action: "rebuild_index",
    usedAntibody: false,
    learnedAntibody: "ab-3",
    coveredClass: "dependency_outage",
    mttr: 47,
    metricLabel: "retrieval_health",
    metricBad: "0.30",
    metricGood: "0.98",
    steps: [
      { stage: "act", text: "approved by oncall · rebuild_index → recovered" },
      { stage: "verify", text: "verified healthy · MTTR 47s" },
      { stage: "reflect", text: "postmortem written" },
      { stage: "immunize", text: "🧬 fleet immunized · antibody ab-3" },
    ],
  },
];

export const MTTR_SERIES = NARRATIVE.filter((b) => b.mttr > 0).map((b) => ({
  label: b.serviceName,
  mttr: b.mttr,
  antibody: b.usedAntibody,
}));
